package edge.metadata.annotation

uses gw.lang.reflect.IPropertyInfo


/**
 * Metadata factory aware of the property on which it was set.
 */
interface IPropertyAwareMetaMultiFactory extends IAnnotation{
  /**
   * Returns a representation of the metadata items generated by this metadata factory.
   * @param prop property on which this annotation is set.
   */
  public function getState(prop : IPropertyInfo) : Object[]
}
