package edge.metadata.annotation

uses gw.lang.reflect.IType

/**
 * Metadata factory aware of the type on which it was set.
 */
interface ITypeAwareMetaFactory extends IAnnotation{
  /**
   * Returns a representation of the metadata generated by this metadata factory.
   * @param type type on which this annotation is set.
   */
  public function getState(type : IType) : Object
}
